### ISSUE TITLE
Move phel-json library to phel-lang core

### ISSUE THREAD

**Issue by Chemaclass** [mabasic/phel-json#2]
Related to https://github.com/phel-lang/phel-lang/issues/59#issuecomment-968108756

I thought it would be useful to create an issue in this repo to don't forget about this awesome phel-json utility, so we can have it in the phel core as `json.phel` and everyone can benefit from it.

The best is that you (@mabasic) are the one that create the file and the PR because it's your code, and you surely like to contribute with your name in the project too :) 

But let me know if you need help anyhow to do this.

**Comment by mabasic** [comment]
I am planning to do this :) That was the plan from the beginning. I've created this library in order to help me write: **Documentation for Library-Developers** https://github.com/phel-lang/phel-lang/issues/59

The library is complete and the process works. I only need to write the steps in a markdown file. My idea was for people to be able to see the whole process with how a published library looks and works.

I hope that this weekend I will be able to work on this. Thank you for a reminder.
